### ISSUE TITLE
Convert a docker-compose.yml file to terraform

### ISSUE THREAD

**Issue by phildini** [galaxybrainco/cloudtower#1]
This ticket is designed to be a long-form research ticket, with me working in public as I work out the first version of python script to convert a specific docker-compose file (ideally, the one from https://github.com/bookwyrm-social/bookwyrm) into a set of terraform files that I actually believe will do the thing. 

Here's the steps as I see them:

- [x] Parse the docker-compose.yml file in python so I can get a handle on what services are exposed
- [ ] Explore terraform resource naming flexibility
- [ ] Templatize a reasonable terraform config for AWS that uses ECS, Fargate, RDS, ELB, and S3
- [ ] wire these pieces together
- [ ] write tests that prove out this does what it says it does

**Comment by phildini** [comment]
Ok, this did not take long, but I'm already vaguely annoyed at bookwyrm's docker-compose.yml, specifically because of:

```
  db:
    build: postgres-docker
    env_file: .env
    entrypoint: /bookwyrm-entrypoint.sh
    command: cron postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - backups:/backups
    networks:
      - main
```
(https://github.com/bookwyrm-social/bookwyrm/blob/1ff7d836ae595a8e22db8a2e9d4895e19d8dbb1c/docker-compose.yml#L28-L37)

Because they're defining their own postgres container, we don't get to take easy advantage of "knowing" this should actually be an RDS.

Although! Detecting that there's a volume called `pgdata` might be enough?
